name: deploy.yml
on:
  push:
    tags: v*
jobs:
  test-app:
    runs-on: ubuntu-latest
    env:
      POSTFOLIO_ENV: ${{ secrets.POSTFOLIO_ENV }}
      POSTFOLIO_SECRET_KEY: ${{ secrets.POSTFOLIO_SECRET_KEY }}
      POSTFOLIO_DATABASE_URL: PLACE_HOLDER
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Build & Execute
        run: |
          echo "POSTFOLIO_ENV=${POSTFOLIO_ENV}" >> .env
          echo "POSTFOLIO_SECRET_KEY=${POSTFOLIO_SECRET_KEY}" >> .env
          echo "POSTFOLIO_DATABASE_URL=${POSTFOLIO_DATABASE_URL}" >> .env
          docker compose up -d --build 
      - name: Install Dependencies
        run: pip install -r requirements-dev.txt && pip install -r requirements.txt
      - name: Run Unit Tests
        run: pytest -v ./test/test.py
  deploy:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
  release:
    needs: [ test-app, deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        